// TRAKTOR PRO 3 — Données MIDI (286 assignations)
// Source : Google Sheets officiel (extrait du PDF TRAKTORPRO3AssignementsMIDI.pdf)
// Descriptions traduites en français

export interface MidiControl {
  categorie: string;
  nom: string;
  description: string;
  type: "Entrée/Sortie" | "Entrée" | "Sortie";
}

export const MIDI_DATA: MidiControl[] = [
  // ── AUDIO RECORDER (4) ──────────────────────────────────────
  { categorie: "AUDIO RECORDER", nom: "Record/Stop", description: "Démarre/arrête l'enregistrement de l'AUDIO RECORDER", type: "Entrée/Sortie" },
  { categorie: "AUDIO RECORDER", nom: "Cut", description: "Coupe l'audio à la position actuelle et commence un nouveau fichier", type: "Entrée/Sortie" },
  { categorie: "AUDIO RECORDER", nom: "Gain Adjust", description: "Ajuste le gain de l'AUDIO RECORDER", type: "Entrée/Sortie" },
  { categorie: "AUDIO RECORDER", nom: "Load Last Recording", description: "Charge le dernier enregistrement audio dans un Deck", type: "Entrée/Sortie" },
  // ── Browser (56) ────────────────────────────────────────────
  { categorie: "Browser", nom: "List > Delete", description: "Supprime un fichier de la collection de pistes", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Reset Played-State", description: "Réinitialise l'état 'joué' du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Analyze", description: "Analyse le fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Restore Auto-Gain", description: "Restaure la valeur d'auto-gain du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Detect BPM", description: "Détecte le BPM du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > BPM Unlock", description: "Déverrouille le BPM du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > BPM Lock", description: "Verrouille le BPM du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Edit", description: "Affiche les métadonnées modifiables du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Relocate", description: "Relocalise le fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Add as Track To Collection", description: "Ajoute le(s) fichier(s) à la collection et définit le type comme piste", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Add as One-Shot Sample To Collection", description: "Ajoute le(s) fichier(s) à la collection et définit le type comme sample one-shot", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Add as Loop To Collection", description: "Ajoute le(s) fichier(s) à la collection et définit le type comme sample en boucle", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Set to One-Shot Sample", description: "Définit le type du fichier sélectionné comme sample one-shot", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Set to Looped Sample", description: "Définit le type du fichier sélectionné comme sample en boucle", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Set to Track", description: "Définit le type du fichier sélectionné comme piste", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Up/Down", description: "Fait défiler la liste de pistes vers le haut/bas d'un fichier", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Page Up/Down", description: "Fait défiler la liste de pistes vers le haut/bas d'une page", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Top/Bottom", description: "Fait défiler jusqu'au premier/dernier fichier de la liste", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Extend Up/Down", description: "Étend la sélection d'un fichier vers le haut/bas", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Extend Page Up/Down", description: "Étend la sélection d'une page vers le haut/bas", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select Extend Top/Bottom", description: "Étend la sélection jusqu'à tous les fichiers vers le haut/bas", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Select All", description: "Sélectionne tous les fichiers de la liste de pistes", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Consolidate", description: "Renumérotise la liste de lecture selon l'ordre actuel", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Search", description: "Déplace le curseur dans le champ de recherche pour démarrer une recherche", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Search Clear", description: "Efface la recherche en cours", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Search in Playlists", description: "Affiche un popup avec toutes les listes de lecture contenant le fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Show In Explorer", description: "Navigue dans l'explorateur jusqu'au chemin physique du fichier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Clear", description: "Efface la liste", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Expand Content Set", description: "Affiche le contenu du Remix Set sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Jump To Current Track", description: "Saute à la dernière piste chargée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Append To Preparation List", description: "Ajoute la piste sélectionnée à la fin de la liste de préparation", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Add As Next To Preparation List", description: "Ajoute la piste à la liste de préparation juste après la dernière piste chargée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "List > Export as Remix Set", description: "Exporte un fichier Remix Set", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Save Collection", description: "Sauvegarde la collection sur le disque dur", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Delete", description: "Supprime l'élément sélectionné dans l'arborescence", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Reset Played-State", description: "Réinitialise l'état 'joué' de la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Analyze", description: "Analyse le contenu de la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Restore AutoGain", description: "Restaure l'auto-gain pour le contenu de la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Edit", description: "Affiche les métadonnées modifiables de la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Relocate", description: "Relocalise la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Import Collection", description: "Importe une autre collection de pistes", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Import Music Folders", description: "Importe de nouveaux fichiers depuis les dossiers musicaux", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Export", description: "Exporte la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Export Printable", description: "Exporte la liste de lecture sélectionnée en page web", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Rename Playlist or Folder", description: "Renomme la liste de lecture ou le dossier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Select Up/Down", description: "Navigue vers le haut/bas d'un dossier dans l'arborescence du navigateur", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Select Expand/Collapse", description: "Développe/réduit le dossier sélectionné dans l'arborescence", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Create Playlist", description: "Crée une nouvelle liste de lecture dans le dossier sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Delete Playlist", description: "Supprime la liste de lecture sélectionnée", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Create Playlist Folder", description: "Crée un nouveau dossier de listes de lecture", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Delete Playlist Folder", description: "Supprime le dossier de listes de lecture sélectionné", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Refresh Explorer Folder Content", description: "Actualise le contenu du dossier de l'explorateur", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Check Consistency", description: "Vérifie la cohérence de la collection de pistes et affiche un rapport", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Tree > Add Folder To Music Folders", description: "Ajoute un dossier musical au dossier de l'explorateur", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Favorites > Selector", description: "Sélectionne l'une des listes de lecture favorites", type: "Entrée/Sortie" },
  { categorie: "Browser", nom: "Favorites > Add Selected Tracks To Favorite", description: "Ajoute les pistes sélectionnées à la liste de favoris mappée", type: "Entrée/Sortie" },
  // ── Deck Common (50) ────────────────────────────────────────
  { categorie: "Deck Common", nom: "Load Next", description: "Charge la piste suivante de la liste en cours dans le Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Load Previous", description: "Charge la piste précédente de la liste en cours dans le Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Load Selected", description: "Charge la piste sélectionnée dans le Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Unload", description: "Décharge la piste du Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Play/Pause", description: "Lecture/pause du Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Cue", description: "Retour au point Cue flottant actuel", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "CUP (Cue Play)", description: "Retour au point Cue flottant et démarrage immédiat de la lecture", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Seek Position", description: "Avance/recule dans la piste", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Jog Touch On", description: "Mappe la platine supérieure du jog wheel. Pendant la lecture, arrête la piste et active le mode Scratch", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Jog Turn", description: "Mappe le jog wheel pour le pitch bend. Avec Jog Touch On, active le scratching pendant la lecture", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Set as Tempo Master", description: "Définit un Deck comme Tempo Master", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Sync On", description: "Active la synchronisation pour un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Phase Sync", description: "Synchronise la phase d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Tempo Sync", description: "Synchronise le tempo d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Tempo Bend", description: "Augmente/diminue temporairement la vitesse de lecture par paliers", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Tempo Bend (stepless)", description: "Augmente/diminue temporairement la vitesse de lecture de façon continue", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Tempo Adjust", description: "Ajuste le tempo d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Tempo Range Selector", description: "Définit la plage de tempo d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Keylock On", description: "Active/désactive le Keylock pour un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Keylock On (Preserve Pitch)", description: "Active/désactive le Keylock en préservant la hauteur tonale actuelle", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Key Adjust", description: "Ajuste la tonalité d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Analyze Loaded Track", description: "Lance l'analyse de la piste chargée dans un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Deck Flavor Selector", description: "Définit le type de Deck : Track Deck, Remix Deck, STEM Deck ou Live Input", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Deck Size Selector", description: "Définit la taille du Deck : Micro, Small, Essential, Full ou Advanced", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Advanced Panel Toggle", description: "Affiche/masque le panneau avancé pour deux Decks correspondants", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Advanced Panel Tab Selector", description: "Sélectionne l'onglet MOVE, CUE ou GRID dans le panneau avancé", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Timecode > Scratch Control On", description: "Active/désactive le contrôle Scratch pour un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Timecode > Playback Mode Int/Rel/Abs", description: "Définit le mode de lecture : Interne, Relatif ou Absolu", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Timecode > Platter/Scope View Selector", description: "Définit la vue Platter/Scope : Off, Minimisé, Platter ou Scope", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Timecode > Calibrate", description: "Lance la calibration du signal timecode d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Timecode > Reset Tempo Offset", description: "Réinitialise le décalage de tempo d'un Deck en mode scratch control", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Move > Size Selector", description: "Définit la taille du déplacement", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Move > Mode Selector", description: "Définit le mode de déplacement : beatjump, loop, loop in ou loop out", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Move > Move", description: "Initie un déplacement vers l'avant ou l'arrière", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Move > Beatjump", description: "Définit la longueur du beatjump et l'initie directement", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop In/Set Cue", description: "Définit le point d'entrée de boucle / point Cue flottant", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop Out", description: "Définit le point de sortie de boucle et active la boucle", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop Size Selector", description: "Définit la taille de la boucle automatique", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop Set", description: "Définit une boucle automatique à la position de lecture et l'active", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop Size Select + Set", description: "Définit la taille de boucle et active une boucle automatique à la position de lecture", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Backward Loop Size Select + Set", description: "Définit la taille et active une boucle automatique en arrière à la position de lecture", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Loop > Loop Active On", description: "Active/désactive toutes les boucles", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Phase", description: "Renvoie la valeur du compteur de phase (0 = phases alignées)", type: "Sortie" },
  { categorie: "Deck Common", nom: "Beat Phase", description: "Renvoie la distance jusqu'à la prochaine ligne de grille (0 = sur la grille)", type: "Sortie" },
  { categorie: "Deck Common", nom: "Deck is Loaded", description: "Indique si une piste est chargée dans un Deck", type: "Sortie" },
  { categorie: "Deck Common", nom: "Is In Active Loop", description: "Renvoie 1 si la piste est en boucle, 0 sinon", type: "Sortie" },
  { categorie: "Deck Common", nom: "Freeze Mode > Freeze Mode On", description: "Active/désactive le mode Freeze", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Freeze Mode > Freeze Slice Size Adjust", description: "Définit la taille des tranches (Slices)", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Freeze Mode > Freeze Slice Count Adjust", description: "Définit le nombre de tranches à mapper sur le contrôleur", type: "Entrée/Sortie" },
  { categorie: "Deck Common", nom: "Freeze Mode > Slice Trigger (1-16)", description: "Liste des déclencheurs de tranches individuels (1-16) assignables à un contrôleur", type: "Entrée/Sortie" },
  // ── FX Unit (14) ────────────────────────────────────────────
  { categorie: "FX Unit", nom: "Unit On", description: "Active/désactive une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Dry/Wet Adjust", description: "Ajuste le rapport dry/wet d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Knob 1", description: "Contrôle le bouton 1 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Knob 2", description: "Contrôle le bouton 2 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Knob 3", description: "Contrôle le bouton 3 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Button 1", description: "Active/désactive le bouton 1 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Button 2", description: "Active/désactive le bouton 2 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Button 3", description: "Active/désactive le bouton 3 d'une unité FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Effect 1 Selector", description: "Sélectionne l'effet 1 d'une unité FX (mode Group ou Single)", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Effect 2 Selector", description: "Sélectionne l'effet 2 d'une unité FX en mode Group", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Effect 3 Selector", description: "Sélectionne l'effet 3 d'une unité FX en mode Group", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "FX Unit Mode Selector", description: "Bascule une unité FX en mode Group FX ou Single FX", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "FX Store Preset", description: "Sauvegarde les paramètres actuels d'une unité FX comme préréglage", type: "Entrée/Sortie" },
  { categorie: "FX Unit", nom: "Effect LFO Reset", description: "Réinitialise le LFO d'une unité FX", type: "Entrée/Sortie" },
  // ── Global (7) ──────────────────────────────────────────────
  { categorie: "Global", nom: "Snap On", description: "Active/désactive le mode Snap", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Quant On", description: "Active/désactive le mode Quantize", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Broadcasting On", description: "Active/désactive la diffusion (broadcasting)", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Cruise Mode On", description: "Active/désactive le mode Cruise", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Show Slider Values On", description: "Active/désactive l'affichage des valeurs de chaque curseur", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Tool Tips On", description: "Active/désactive les infobulles", type: "Entrée/Sortie" },
  { categorie: "Global", nom: "Send Monitor State", description: "Envoie l'état actuel à tous les boutons LED", type: "Entrée/Sortie" },
  // ── Layout (5) ──────────────────────────────────────────────
  { categorie: "Layout", nom: "Only Browser On", description: "Maximise le navigateur", type: "Entrée/Sortie" },
  { categorie: "Layout", nom: "Layout Selector", description: "Sélectionne l'une des dispositions TRAKTOR", type: "Entrée/Sortie" },
  { categorie: "Layout", nom: "Fullscreen On", description: "Active/désactive le mode plein écran", type: "Entrée/Sortie" },
  { categorie: "Layout", nom: "Deck Focus Selector", description: "Bascule le focus du Deck / définit le Deck focalisé", type: "Entrée/Sortie" },
  { categorie: "Layout", nom: "Toggle Last Focus", description: "Bascule le focus entre le dernier Deck et le Deck actuel", type: "Entrée/Sortie" },
  // ── Loop Recorder (9) ───────────────────────────────────────
  { categorie: "Loop Recorder", nom: "Record", description: "Démarre/arrête l'enregistrement du LOOP RECORDER", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Size", description: "Définit la taille d'enregistrement du LOOP RECORDER", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Dry/Wet Adjust", description: "Ajuste le rapport dry/wet du LOOP RECORDER", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Play/Pause", description: "Démarre/arrête la lecture de la boucle enregistrée", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Delete", description: "Supprime la boucle enregistrée", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Undo/Redo", description: "Annule/rétablit la dernière action du LOOP RECORDER", type: "Entrée/Sortie" },
  { categorie: "Loop Recorder", nom: "Playback Position", description: "Renvoie la position de lecture du LOOP RECORDER (plage : 0 à 1)", type: "Sortie" },
  { categorie: "Loop Recorder", nom: "Undo State", description: "Renvoie l'état d'annulation du LOOP RECORDER", type: "Sortie" },
  { categorie: "Loop Recorder", nom: "State", description: "Renvoie l'état du LOOP RECORDER", type: "Sortie" },
  // ── Master Clock (11) ───────────────────────────────────────
  { categorie: "Master Clock", nom: "Ableton Link > Reset Downbeat", description: "Synchronise sur le prochain temps fort", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Auto Master Mode", description: "Passe le Master Clock en mode automatique", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Master Tempo Selector", description: "Définit la source du Tempo Master : Clock, Deck A, B, C ou D", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Set Tempo Master", description: "Ajuste le tempo du Master Clock", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Tempo Bend Up", description: "Augmente temporairement le tempo", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Tempo Bend Down", description: "Diminue temporairement le tempo", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Beat Tap", description: "Définit le tempo en le tapant", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Tick On", description: "Active/désactive le métronome du Master Clock", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Clock Int/Ext", description: "Bascule le Master Clock entre interne et externe", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Clock Send", description: "Active/désactive l'envoi de l'horloge MIDI", type: "Entrée/Sortie" },
  { categorie: "Master Clock", nom: "Clock Trigger MIDI Sync", description: "Déclenche la synchronisation de l'horloge MIDI (MIDI Start)", type: "Entrée/Sortie" },
  // ── Mixer (33) ──────────────────────────────────────────────
  { categorie: "Mixer", nom: "Gain Adjust", description: "Ajuste le gain d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Auto-Gain Adjust", description: "Active/désactive l'Auto-Gain", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Auto-Gain View On", description: "Active/désactive l'affichage de la fonction Gain pour le canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "FX Unit 1 On", description: "Engage/désengage l'unité FX 1 sur un Deck", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "FX Unit 2 On", description: "Engage/désengage l'unité FX 2 sur un Deck", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "FX Unit 3 On", description: "Engage/désengage l'unité FX 3 sur un Deck", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "FX Unit 4 On", description: "Engage/désengage l'unité FX 4 sur un Deck", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Deck Effect On", description: "Assigne/désassigne l'unité FX correspondante à un Deck", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Mixer FX Adjust", description: "Ajuste la quantité de Mixer FX pour un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Mixer FX On", description: "Active/désactive le Mixer FX pour un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Mixer FX Selector", description: "Sélectionne le Mixer FX", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Balance Adjust", description: "Ajuste la balance d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Monitor Cue On", description: "Active/désactive l'envoi de l'audio d'un canal vers le canal CUE", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Volume Adjust", description: "Ajuste le volume d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Master Volume Adjust", description: "Ajuste le volume de sortie Master", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Limiter On", description: "Active/désactive le limiteur", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Monitor Volume Adjust", description: "Ajuste le volume du canal CUE", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Monitor Mix Adjust", description: "Ajuste le mix entre le signal Master et le signal CUE", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "Microphone Gain Adjust", description: "Ajuste le gain du microphone", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > High Adjust", description: "Ajuste les hautes fréquences d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > High Kill", description: "Active/désactive la coupure des hautes fréquences d'un canal", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > Mid Adjust", description: "Ajuste les fréquences médiums d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > Mid Kill", description: "Active/désactive la coupure des fréquences médiums d'un canal", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > MidLow Adjust", description: "Ajuste les fréquences médium-basses d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > MidLow Kill", description: "Active/désactive la coupure des fréquences médium-basses d'un canal", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > Low Adjust", description: "Ajuste les basses fréquences d'un canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "EQ > Low Kill", description: "Active/désactive la coupure des basses fréquences d'un canal", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Position", description: "Définit la position du crossfader", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Curve Adjust", description: "Ajuste la courbe du crossfader entre douce et tranchante", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Assign Left", description: "Assigne/désassigne un Deck au côté gauche du crossfader", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Assign Right", description: "Assigne/désassigne un Deck au côté droit du crossfader", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Auto X-Fade Left", description: "Effectue un crossfade automatique vers la gauche", type: "Entrée/Sortie" },
  { categorie: "Mixer", nom: "X-Fader > Auto X-Fade Right", description: "Effectue un crossfade automatique vers la droite", type: "Entrée/Sortie" },
  // ── Modifier (8) ────────────────────────────────────────────
  { categorie: "Modifier", nom: "Modifier #1", description: "Définit le modificateur #1", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #2", description: "Définit le modificateur #2", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #3", description: "Définit le modificateur #3", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #4", description: "Définit le modificateur #4", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #5", description: "Définit le modificateur #5", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #6", description: "Définit le modificateur #6", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #7", description: "Définit le modificateur #7", type: "Entrée/Sortie" },
  { categorie: "Modifier", nom: "Modifier #8", description: "Définit le modificateur #8", type: "Entrée/Sortie" },
  // ── Preview Player (4) ──────────────────────────────────────
  { categorie: "Preview Player", nom: "Load Selected", description: "Charge la piste sélectionnée dans le Preview Player", type: "Entrée/Sortie" },
  { categorie: "Preview Player", nom: "Play/Pause", description: "Démarre/arrête la lecture du Preview Player", type: "Entrée/Sortie" },
  { categorie: "Preview Player", nom: "Seek Position", description: "Cherche la position dans le Preview Player", type: "Entrée/Sortie" },
  { categorie: "Preview Player", nom: "Unload", description: "Décharge le Preview Player", type: "Entrée/Sortie" },
  // ── Remix Deck (46) ─────────────────────────────────────────
  { categorie: "Remix Deck", nom: "Save Remix Set", description: "Sauvegarde le contenu d'un Remix Deck comme Remix Set", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Load Set from List", description: "Charge un Remix Set depuis la liste de pistes du navigateur", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Volume Adjust", description: "Ajuste le volume d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Filter On", description: "Active/désactive le filtre d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Filter Adjust", description: "Ajuste le filtre d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Capture/Trigger/Mute", description: "Capture un sample, le déclenche, puis bascule entre muet et non muet", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Mute On", description: "Met en sourdine / réactive un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Stop/Delete/Load from List", description: "Arrête la lecture si en cours, décharge si arrêté, charge depuis la liste si vide", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Retrigger", description: "Redéclenche la lecture d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Play Mode", description: "Définit le mode de lecture d'un emplacement : boucle ou one-shot", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Keylock On", description: "Active/désactive le keylock d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot State", description: "Renvoie l'état d'un emplacement de sample", type: "Sortie" },
  { categorie: "Remix Deck", nom: "Slot FX On", description: "Engage/désengage l'emplacement vers l'unité FX assignée au canal du Mixer", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Monitor On", description: "Active/désactive l'envoi de l'audio d'un emplacement vers le canal CUE", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Slot Punch On", description: "Active/désactive le mode Punch pour un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Quantize Selector", description: "Sélectionne la valeur de quantification du Remix Deck", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Quantize On", description: "Active/désactive le mode Quantize pour le Remix Deck", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Capture Source Selector", description: "Sélectionne la source (Track Deck ou LOOP RECORDER) pour la capture", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Sample Page Selector", description: "Bascule entre les quatre pages de samples du Remix Set", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Play All Slots", description: "Démarre/arrête la lecture de tous les emplacements d'un Remix Deck", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Trigger All Slots", description: "Déclenche tous les emplacements de sample d'un Remix Deck", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Retrigger Play", description: "Démarre la lecture d'un emplacement depuis le début", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Load from List", description: "Charge le sample sélectionné dans un emplacement", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Unload", description: "Décharge un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Capture from Deck", description: "Capture l'audio d'un Track Deck et le place dans un emplacement", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Capture from Loop Recorder", description: "Capture l'audio du Loop Recorder et le place dans un emplacement", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Copy from Slot", description: "Copie le sample d'un emplacement vers un autre", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Play Mode All Slots", description: "Bascule le mode de lecture entre boucle et one-shot pour tous les emplacements", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Size x2", description: "Double la taille d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Size /2", description: "Divise par deux la taille d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Size Reset", description: "Réinitialise la taille d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Legacy > Slot Size Adjust", description: "Ajuste la taille d'un emplacement de sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Slot X Cell Y Trigger", description: "Déclenche la cellule de sample spécifiée selon ses paramètres de lecture", type: "Entrée" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Slot X Cell Y State", description: "Renvoie l'état de lecture actuel de la cellule (Vide, Chargé, En lecture)", type: "Sortie" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Cell Load Modifier", description: "Maintenir pour charger le sample sélectionné depuis le navigateur dans la cellule", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Cell Delete Modifier", description: "Maintenir tout en déclenchant une cellule pour supprimer le sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Cell Reverse Modifier", description: "Maintenir et tenir une cellule pour inverser la direction de lecture du sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Direct Mapping > Capture Modifier", description: "Maintenir tout en déclenchant une cellule pour capturer un sample depuis la source", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Meters > Slot Pre-Fader Level (L)", description: "Renvoie le niveau pré-fader (G) d'un emplacement de sample", type: "Sortie" },
  { categorie: "Remix Deck", nom: "Meters > Slot Pre-Fader Level (R)", description: "Renvoie le niveau pré-fader (D) d'un emplacement de sample", type: "Sortie" },
  { categorie: "Remix Deck", nom: "Meters > Slot Pre-Fader Level (L+R)", description: "Renvoie le niveau pré-fader (G+D) d'un emplacement de sample", type: "Sortie" },
  { categorie: "Remix Deck", nom: "Step Sequencer > Sequencer On", description: "Active l'enregistreur de patterns", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Step Sequencer > Swing Amount", description: "Maintenir ce modificateur et tourner l'encodeur pour ajuster la longueur du pattern", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Step Sequencer > Selected Sample", description: "Maintenir ce modificateur pour sélectionner un autre sample", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Step Sequencer > Pattern Length", description: "Définit la longueur du pattern du sample sélectionné", type: "Entrée/Sortie" },
  { categorie: "Remix Deck", nom: "Step Sequencer > Enable Step 1 to 16", description: "Active ou désactive les étapes 1 à 16", type: "Entrée/Sortie" },
  // ── Track Deck (39) ─────────────────────────────────────────
  { categorie: "Track Deck", nom: "Load into Next Stopped Deck", description: "Charge la piste sélectionnée dans le premier Deck arrêté disponible", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Load, Loop, and Play", description: "Charge la piste, place le cue sur le marqueur de chargement, définit une boucle et lance la lecture", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Duplicate Track Deck A", description: "Duplique la piste chargée du Deck A dans un Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Duplicate Track Deck B", description: "Duplique la piste chargée du Deck B dans un Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Duplicate Track Deck C", description: "Duplique la piste chargée du Deck C dans un Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Duplicate Track Deck D", description: "Duplique la piste chargée du Deck D dans un Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Waveform Zoom Adjust", description: "Ajuste le zoom de la forme d'onde d'un Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "DAW View", description: "Affiche/masque la vue DAW sur un STEM Deck", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Keylock On", description: "Active/désactive le Keylock", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Keylock On (Preserve Pitch)", description: "Active/désactive le Keylock en préservant la hauteur tonale", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Key Adjust", description: "Ajuste la valeur de la tonalité", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Set Cue and Store as next Hotcue", description: "Définit un point Cue et le sauvegarde comme prochain Hotcue disponible", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Store Floating Cue/Loop as next Hotcue", description: "Sauvegarde le cue/boucle flottant comme prochain Hotcue disponible", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Delete current Hotcue", description: "Supprime le Hotcue actuel", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Jump to Next/Prev Cue/Loop", description: "Saute au point Cue ou à la boucle précédent(e)/suivant(e)", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Map Hotcue", description: "Mappe le point Cue flottant sur un Hotcue", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Select/Set+Store Hotcue", description: "Définit et sauvegarde un Hotcue à la position de lecture, ou y saute s'il existe", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Delete Hotcue", description: "Supprime un Hotcue", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Cue > Cue Type Selector", description: "Définit le type de cue (cue, fade-in, fade-out, load, grid ou loop) pour un Hotcue", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 1 Type", description: "Renvoie le type du Hotcue 1", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 2 Type", description: "Renvoie le type du Hotcue 2", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 3 Type", description: "Renvoie le type du Hotcue 3", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 4 Type", description: "Renvoie le type du Hotcue 4", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 5 Type", description: "Renvoie le type du Hotcue 5", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 6 Type", description: "Renvoie le type du Hotcue 6", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 7 Type", description: "Renvoie le type du Hotcue 7", type: "Sortie" },
  { categorie: "Track Deck", nom: "Hotcue 8 Type", description: "Renvoie le type du Hotcue 8", type: "Sortie" },
  { categorie: "Track Deck", nom: "Grid > Autogrid", description: "Lance l'analyse de la piste et définit le BPM et un marqueur de beatgrid", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Reset BPM", description: "Lance le recalcul du BPM", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Copy Phase from Tempo Master", description: "Copie la phase depuis le Tempo Master", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Set Grid Marker", description: "Définit un marqueur de beatgrid à la position de lecture actuelle", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Delete Grid Marker", description: "Supprime le dernier marqueur de beatgrid", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Move Grid Marker", description: "Déplace un marqueur de beatgrid", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > BPM Adjust", description: "Ajuste le BPM de la piste", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > BPM Lock On", description: "Empêche la modification du BPM d'une piste lorsqu'activé", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > BPM x2", description: "Double la valeur du BPM de la piste", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > BPM /2", description: "Divise par deux le BPM de la piste", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Beat Tap", description: "Définit le BPM de la piste en le tapant", type: "Entrée/Sortie" },
  { categorie: "Track Deck", nom: "Grid > Tick On", description: "Active/désactive le son de tick sur le temps", type: "Entrée/Sortie" },
  // ── Commandes Virtuelles (8 Buttons + 8 Knobs + 8 Faders) ──
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 1", description: "Slot de bouton virtuel global #1 — assignable à n’importe quelle action TRAKTOR via le Controller Manager. Supporte les modes Hold, Toggle et Direct. Utilisé typiquement pour Play/Pause, Hotcue 1 ou activation FX.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 2", description: "Slot de bouton virtuel global #2 — souvent utilisé pour Cue, Hotcue 2 ou activation d’une unité FX.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 3", description: "Slot de bouton virtuel global #3 — fréquemment utilisé comme touche Shift/Modifier pour créer des couches de fonctions avec les Buttons 1-2.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 4", description: "Slot de bouton virtuel global #4 — peut servir de second Modifier ou pour des actions de Loop/Sync.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 5", description: "Slot de bouton virtuel global #5 — utilisé dans des macros avancées pour contrôle d’effets ou de transport.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 6", description: "Slot de bouton virtuel global #6 — peut envoyer des messages MIDI sortants vers des applications externes (Ableton, DMX).", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 7", description: "Slot de bouton virtuel global #7 — souvent utilisé pour des actions de navigation Browser ou de sélection de platine.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Button 8", description: "Slot de bouton virtuel global #8 — peut déclencher des actions de recording ou de monitoring.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 1", description: "Slot de potentiomètre virtuel global #1 — contrôle continu assignable à n’importe quel paramètre TRAKTOR (volume, filtre, EQ, tempo). Supporte les modes Direct et Relative.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 2", description: "Slot de potentiomètre virtuel global #2 — souvent utilisé pour le réglage de Dry/Wet FX ou du filtre d’une platine.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 3", description: "Slot de potentiomètre virtuel global #3 — peut contrôler la fréquence d’un LFO ou le tempo du Master Clock.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 4", description: "Slot de potentiomètre virtuel global #4 — utilisé dans des macros pour morphing EQ ou contrôle de volume de stem.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 5", description: "Slot de potentiomètre virtuel global #5 — peut contrôler le gain d’un canal Mixer ou la taille d’une boucle.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 6", description: "Slot de potentiomètre virtuel global #6 — souvent utilisé pour le réglage de la balance ou du monitoring.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 7", description: "Slot de potentiomètre virtuel global #7 — contrôle l’intensité globale des effets (Dry/Wet global). Combiné avec Buttons 1-3 pour des macros avancées.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Knob 8", description: "Slot de potentiomètre virtuel global #8 — utilisé dans les macros de morphing EQ (contrôle simultané High EQ Deck A et B en mode inversé selon Modifier).", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 1", description: "Slot de fader virtuel global #1 — contrôle linéaire assignable à n’importe quel paramètre de type fader (volume, crossfader, loop size). Idéal pour le volume d’une platine.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 2", description: "Slot de fader virtuel global #2 — souvent utilisé pour le volume d’une seconde platine ou pour le réglage du monitor mix.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 3", description: "Slot de fader virtuel global #3 — peut contrôler le volume master ou le gain d’un canal.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 4", description: "Slot de fader virtuel global #4 — utilisé dans des configurations multi-deck pour le volume de la platine C ou D.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 5", description: "Slot de fader virtuel global #5 — peut contrôler la position du crossfader ou le Dry/Wet d’un effet.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 6", description: "Slot de fader virtuel global #6 — souvent utilisé pour des réglages de Stem Volume dans les configurations STEM Deck.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 7", description: "Slot de fader virtuel global #7 — peut contrôler la taille d’enregistrement du Loop Recorder ou le tempo bend.", type: "Entrée/Sortie" },
  { categorie: "Commandes Virtuelles", nom: "MIDI Fader 8", description: "Slot de fader virtuel global #8 — utilisé dans des macros avancées pour des transitions automatiques ou des effets de sweep.", type: "Entrée/Sortie" },
];

// Stats
export const CATEGORIES = Array.from(new Set(MIDI_DATA.map(d => d.categorie)));
export const TOTAL = MIDI_DATA.length;

export const STATS_BY_CATEGORY = CATEGORIES.map(cat => ({
  categorie: cat,
  total: MIDI_DATA.filter(d => d.categorie === cat).length,
  entree_sortie: MIDI_DATA.filter(d => d.categorie === cat && d.type === "Entrée/Sortie").length,
  entree: MIDI_DATA.filter(d => d.categorie === cat && d.type === "Entrée").length,
  sortie: MIDI_DATA.filter(d => d.categorie === cat && d.type === "Sortie").length,
}));

export const TYPE_COLORS: Record<string, string> = {
  "Entrée/Sortie": "#00D4FF",
  "Entrée": "#00FF88",
  "Sortie": "#FF6B35",
};

export const CAT_COLORS: Record<string, string> = {
  "AUDIO RECORDER": "#FF6B6B",
  "Browser": "#4ECDC4",
  "Deck Common": "#45B7D1",
  "FX Unit": "#F7DC6F",
  "Global": "#BB8FCE",
  "Layout": "#85C1E9",
  "Loop Recorder": "#F0B27A",
  "Master Clock": "#52BE80",
  "Mixer": "#F1948A",
  "Modifier": "#AED6F1",
  "Preview Player": "#A9DFBF",
  "Remix Deck": "#82E0AA",
  "Track Deck": "#FAD7A0",
  "Commandes Virtuelles": "#E8A0D4",
};
